### ISSUE TITLE
what is the point of state?

### ISSUE THREAD

**Issue by jwerle** [yoshuawuyts/microcomponent#9]
`state` doesn't seem to be used anywhere
https://github.com/yoshuawuyts/microcomponent/blob/master/index.js#L19

`nanocomponent` doesn't make use of it either

**Comment by f-mer** [comment]
Referring to yoshuawuyts/nanocomponent#25 the intention of `state` is to keep track of the internal state of the component. Everything that can not be computed from the outer application state and passed through the `props` params of the `render` method can be stored there. For example you could keep track if the cursor is hovering over your component.
